### ISSUE TITLE
Add Metro Manila Capital city of Philippines

### ISSUE THREAD

**Issue by cauldyclark15** [benkeen/react-country-region-selector#11]
Hello!

First I want to thank you for your awesome work. May I request your side to add "Metro Manila" in regions of Philippines? Thanks again.

**Comment by benkeen** [comment]
Absolutely! The data is housed under this repo: https://github.com/benkeen/country-region-data

Could you create an issue there with a link to a wikipedia article that lists all the regions of the Philippines - or something that clearly shows the regions and short codes for each. I'll then update it. 

Thanks, @cauldyclark15!
