### ISSUE TITLE
No way to disabled with a value?

### ISSUE THREAD

**Issue by cwhittl** [benkeen/react-country-region-selector#18]
`<CountryDropdown` disabled=true value={country} labelType="short" valueType="short" />

doesn't work

Thanks!

**Comment by benkeen** [comment]
True! `disabled` isn't an option yet. Let me add it to the next version for both CountryDropdown and RegionDropdown. Seems a pretty reasonable addition.

**Comment by benkeen** [comment]
Added in 1.1.0.
