### ISSUE TITLE
onChange returns event.target.value rather than full event

### ISSUE THREAD

**Issue by robertnealan** [benkeen/react-country-region-selector#22]
In many instances I often set a shared `onChange` handler to all inputs in a form, that trigger a common `setState` function that updates the state based on the input name (this seems to be a common pattern as documented by the (https://facebook.github.io/react/docs/forms.html#handling-multiple-inputs)[React Forms Multiple Components section]). Unfortunately it looks like the actual built-in onChange handler only returns the `e.target.value` on lines 48 and 169 rather than the full event, breaking this pattern.

Suggesting an update to return the full event as shown in this commit of my fork (doesn't include the re-built files in this commit): https://github.com/SellingPower/react-country-region-selector/commit/47e5e5893f4b12adbe6e41d0a692cef1b2ba3b5b

Happy to put in a PR if this is of interest to you.

**Comment by nikhil4326** [comment]
can we complete event from component. Is that possible?

**Comment by benkeen** [comment]
Hey @robertnealan, nice! Yeah that makes sense. But how about return the full event as a second param? I think in the majority of cases people will only be interested in the value not the full event, and changing it like this would be a breaking change for existing users. Passing a second param would optionally provide access to the full event. Would that work for your case?

**Comment by robertnealan** [comment]
That sounds reasonable to me, especially since it would keep the component backwards compatible for anyone that's already using it expecting just the target value. I'll put in a PR here in a bit and tag this issue in it.

@nikhil4326 Workin on it! 😉

**Comment by nikhil4326** [comment]
Thanks, That will help.

**Comment by nikhil4326** [comment]
Hi Guys, When will this prop will be available to use?

**Comment by benkeen** [comment]
@robertnealan if you're swamped, no worries let me know and I can add this. Thanks!

**Comment by nikhil4326** [comment]
Yeah Almost. I need this. Please add.

**Comment by robertnealan** [comment]
Super swamped but actually had this ready the other day - just needed to push and PR 😅 

See PR #23

**Comment by benkeen** [comment]
Thanks @robertnealan - all merged! It's in 1.2.2.

**Comment by robertnealan** [comment]
Awesome - thanks @benkeen !
