### ISSUE TITLE
"Viet Nam" is one word "Vietnam"

### ISSUE THREAD

**Issue by asplogic** [benkeen/react-country-region-selector#26]
Correct spelling is Vietnam

**Comment by benkeen** [comment]
Thanks @asplogic - I've created a ticket on the source repo here: https://github.com/benkeen/country-region-selector/issues/59

I'll update that this weekend (or feel free to put in a PR!)

**Comment by benkeen** [comment]
Fixed in 1.2.3. Thanks!
