### ISSUE TITLE
React as peerDependency?

### ISSUE THREAD

**Issue by slopes321** [benkeen/react-country-region-selector#28]
I'm trying to upgrade to React v16 and I'm running into the issue described here:
https://stackoverflow.com/questions/46466253/migration-to-react-16-0-0-error-cannot-find-module-react-lib-reactcomponenttre

I get the output below when I run `yarn list react` and `yarn list react-dom` respectively:

```
$ yarn list react
yarn list v1.2.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ react-country-region-selector@1.2.1
│  └─ react@15.6.1
└─ react@16.0.0
✨  Done in 1.08s.
```

```
$ yarn list react-dom
yarn list v1.2.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ react-country-region-selector@1.2.1
│  └─ react-dom@15.6.1
└─ react-dom@15.4.2
✨  Done in 1.12s.
```

Should `react-country-region-selector` be specifying `react` as a `peerDependency`?

**Comment by benkeen** [comment]
Interesting case this! I just merged in the PR on the issue. I'll release a new version of the lib shortly.
