### ISSUE TITLE
Update release to 1.0.1 to include PR #1

### ISSUE THREAD

**Issue by thetimbanks** [benkeen/react-country-region-selector#3]
In order to get the updated `main` path in https://github.com/benkeen/react-country-region-selector/pull/1 a new release needs to be pushed out. Would you mind pushing out a new release to include this PR?

Thanks.

**Comment by benkeen** [comment]
Gah, apologies. No problem - I'll get a new version out tonight.

**Comment by thetimbanks** [comment]
No problem! Thanks for the update. :+1:

**Comment by benkeen** [comment]
Done! 1.0.1 is now available. I also updated the data source to the latest version (https://github.com/benkeen/country-region-data)

**Comment by thetimbanks** [comment]
Thank you! And thank you for the package. It is working great!
