### ISSUE TITLE
Version 1.3.0 not yet published to npm

### ISSUE THREAD

**Issue by leschaller1** [benkeen/react-country-region-selector#34]
This was updated to version 1.3.0 on 3/20/18, but hasn't been published to npm.

https://www.npmjs.com/package/react-country-region-selector?activeTab=versions

**Comment by benkeen** [comment]
Drat, sorry about that @leschaller1 - I'll publish it tonight.

**Comment by leschaller1** [comment]
Thanks @benkeen !

**Comment by benkeen** [comment]
Done!
