### ISSUE TITLE
Component doesn't update when classes change

### ISSUE THREAD

**Issue by leschaller1** [benkeen/react-country-region-selector#35]
One more issue:

I'd like to use dynamic class names on my region dropdown, but the component only updates when the country or region changes:
https://github.com/benkeen/react-country-region-selector/blob/master/src/rcrs.js#L106 

Is there a reason this isn't allowed or can you add an exception for `classes` here so it updates when they change?

**Comment by leschaller1** [comment]
@benkeen Was going to create a PR for this https://github.com/benkeen/react-country-region-selector/compare/master...leschaller1:master but `gulp` updates hundreds of unrelated lines in lib and dist folders. This is a one line change. Let me know if this is ok to open up or if you plan on resolving the issue. If not, please let me know so I can find an alternate workaround.

Thanks!

**Comment by bsansone** [comment]
@leschaller1 We're you able to resolve this? I'm experiencing this issue as well.
