### ISSUE TITLE
Reactify is deprecated

### ISSUE THREAD

**Issue by zamirkhan** [benkeen/react-country-region-selector#44]
https://github.com/andreypopp/reactify

They recommend switching to babelify. It's also drawing in react-tools, which leads to an NPM warning:

`npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated`

**Comment by benkeen** [comment]
Thanks, @zamirkhan - yeah this repo has gotten a little behind. I'll try to look at it this weekend.

**Comment by benkeen** [comment]
Ah yeah, I remember this now. I used gulp on this repo just to try it out compared to grunt. Boy, this IS old. 

I think I'm actually going to upgrade the whole repo... it's so dated, even the code.

**Comment by benkeen** [comment]
This has been removed with 1.4.0. I'll be releasing it in the next few days. Closing!
