### ISSUE TITLE
Missing autocomplete

### ISSUE THREAD

**Issue by SimonSchick** [benkeen/react-country-region-selector#47]
can you please pass-through that attribute?

**Comment by benkeen** [comment]
Yeah absolutely. I'll include this in the next release. Thanks!

**Comment by SimonSchick** [comment]
In general you might want to thing about doing a pass through of arbitrary attributes to avoid problems like these in the future.
One approach I have seen is using rest destructuring, however that would probably require some transpiler (babel/TS).

**Comment by benkeen** [comment]
I've added in the option to pass arbitrary properties, but for HTML `<select>` elements, I don't think the autoComplete attribute does anything. No? 

I just stumbled across the `<datalist>` HTML element which I'm absolutely staggered I've never heard of before. Is this something like the functionality you had in mind @SimonSchick?
https://jsfiddle.net/shivamrajput/v1duL6y1/

**Comment by SimonSchick** [comment]
`autocomplete` inserts user data automatically for autofill, it works for basically all input types.

**Comment by benkeen** [comment]
Ah, gotcha. Yeah this has been added in the latest code and will be in 1.4. Closing!
